plugin: aws_ec2
regions:
  - ap-south-1
filters:
  tag:Name: miniserver-*
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: role
compose:
  ansible_host: instance_id
  ansible_connection: "'community.aws.aws_ssm'"
  ansible_aws_ssm_region: "'ap-south-1'"
