input {
 cloudwatch_logs {
    log_group =>  ["/miniserver/system", "/miniserver/docker"]
    region => "ap-south-1"
    start_position => "end"
 }
}


filter {
  mutate {
     add_field => { "source_type" => "ec2"}
  }
}



output {
  elasticsearch {
       hosts => ["http://elasticsearch:9200"]
       index => "ec2-logs-%{+YYYY.MM.dd}"
  }
}