input {
 cloudwatch_logs {
    log_group =>  ["/miniserver/system", "/miniserver/docker"]
    region => "ap-south-1"
    start_position => "end"
    tags => ["cloudwatch"]
 }
 file {
   id => "custom-manual-logs"
   path => "/usr/share/logstash/manual-logs/*.json"
   start_position => "beginning"
   sincedb_path => "/dev/null"
   codec => "json"
   tags => ["custom_dashboard"]
 }
}


filter {
 if "cloudwatch" in [tags] {
  mutate {
     add_field => { "data_source" => "cloudwatch"}
  }
}

 if "custom_dashboard" in [tags] {
    mutate {
      add_field => { "data_source" => "custom_dashboard" }
    }
  }
}

output {
  if "cloudwatch" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ec2-logs-%{+YYYY.MM.dd}"
    }
  }
  if "custom_dashboard" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "custom-dashboard-logs-%{+YYYY.MM.dd}"
    }
  }
}