name: Terraform
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# defaults:
#   run:
#     working-directory: modules

jobs:
  #job number 1 : Prepare and Plan and Validate
  terraform-init-format-validate:
    name: Init, Format & Validate
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        #run: terraform fmt -write=true
        run: terraform fmt --recursive

      - name: Terraform Validate
        run: terraform validate

  #Job 2: Plan (depends on validate)
  terraform-plan:
    name: Terraform validate and plan
    runs-on: ubuntu-latest
    needs: terraform-init-format-validate
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  infracost-check:
    name: Cost Check
    runs-on: ubuntu-latest
    needs: [terraform-plan]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY}}

      - name: Run Infracost
        working-directory: .
        run: |
          # Show full breakdown table 
          infracost breakdown  --path . --format table

          # chcek if cost exceeds threshold
          COST=$(infracost breakdown  --path . --format json  | jq -r '.totalMonthlyCost')
          echo "Total monthly cost: $COST "

          if (( $(echo "$COST > 10" | bc -l) )); then
            echo "Cost exceeds \$10 threshold"
          fi

  # Don't exit - just warn exit 1

  ### Terraform Apply
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        #run: terraform apply -auto-approve tfplan
